import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";

import { ToastContainer } from "react-toastify";

import { PropsWithChildren } from "react";
import { Header } from "@/component/HeaderFooter/Header";
import { Footer } from "@/component/HeaderFooter/Footer";
import { CssBaseline, Stack, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Theme } from "@/theme";
import { AuthProvider } from "@/component/AupthProvider";
import { AupthFood } from "@/component/AupthFood";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={Theme}>
            <Stack>
              <AuthProvider>
                <AupthFood>
                  <Header />
                  {children}
                  <Footer />
                </AupthFood>
              </AuthProvider>
            </Stack>
          </ThemeProvider>
          <CssBaseline /> <ToastContainer />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
